# Generated by Django 3.2.4 on 2021-06-25 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aidApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManageProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LoggedIn', models.CharField(max_length=100)),
                ('LoggedResponse', models.CharField(max_length=100)),
                ('Dashboard', models.CharField(max_length=100)),
                ('LogIn', models.CharField(max_length=100)),
                ('SignUp', models.CharField(max_length=100)),
                ('ProfilePage', models.CharField(max_length=100)),
                ('Finish', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='health_practitioner',
            name='AssistanceTimeReady',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='Appointments',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='Login',
            field=models.CharField(default='0000000', editable=False, max_length=100),
        ),
        migrations.CreateModel(
            name='ViewHealthPractitioners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LoggedResponse', models.CharField(max_length=100)),
                ('Dashboard', models.CharField(max_length=100)),
                ('LogIn', models.CharField(max_length=100)),
                ('TalkToDoctor', models.CharField(max_length=100)),
                ('SearchPageDefaultDoctors', models.CharField(max_length=100)),
                ('SearchByKeyWord', models.CharField(max_length=100)),
                ('SearchedResults', models.CharField(max_length=100)),
                ('ClickOnDoctorsName', models.CharField(max_length=100)),
                ('InformationPage', models.CharField(max_length=100)),
                ('ClickOnScheduleAppointment', models.CharField(max_length=100)),
                ('AvailableTimeModal', models.CharField(max_length=100)),
                ('SelectPreferredTimeAddExtraContinue', models.CharField(max_length=100)),
                ('ConfirmationPage', models.CharField(max_length=100)),
                ('Finish', models.CharField(max_length=100)),
                ('LoggedIn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aidApp.patient')),
                ('SignUp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aidApp.manageprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ViewClinicsPharmInLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LoggedIn', models.CharField(max_length=100)),
                ('LoggedResponse', models.CharField(max_length=100)),
                ('Dashboard', models.CharField(max_length=100)),
                ('LogIn', models.CharField(max_length=100)),
                ('SelectPharmaciesClinics', models.CharField(max_length=100)),
                ('SearchPage', models.CharField(max_length=100)),
                ('GrantLocationPermission', models.CharField(max_length=100)),
                ('SelectPharmacyClinicFromPage', models.CharField(max_length=100)),
                ('DefaultResults', models.CharField(max_length=100)),
                ('SearchByKeyWord', models.CharField(max_length=100)),
                ('SearchedResults', models.CharField(max_length=100)),
                ('ClickOnPharmacyClinic', models.CharField(max_length=100)),
                ('InformationPage', models.CharField(max_length=100)),
                ('Finish', models.CharField(max_length=100)),
                ('SignUp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aidApp.manageprofile')),
            ],
        ),
        migrations.AddField(
            model_name='manageprofile',
            name='MyProfile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aidApp.patient'),
        ),
        migrations.AddField(
            model_name='manageprofile',
            name='TalkToDoctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aidApp.health_practitioner'),
        ),
        migrations.CreateModel(
            name='GiveFeedbackCompliants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LoggedResponse', models.CharField(max_length=100)),
                ('Dashboard', models.CharField(max_length=100)),
                ('LogIn', models.CharField(max_length=100)),
                ('SignUp', models.CharField(max_length=100)),
                ('ClickOnContactSupport', models.CharField(max_length=100)),
                ('ContactSupportPage', models.CharField(max_length=100)),
                ('EnterNameEmailChooseCategorySend', models.CharField(max_length=100)),
                ('SuccessfulPage', models.CharField(max_length=100)),
                ('Finish', models.CharField(max_length=100)),
                ('LoggedIn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aidApp.patient')),
            ],
        ),
    ]
