# Generated by Django 3.2.4 on 2021-06-28 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aidApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinic_name', models.CharField(max_length=100)),
                ('open_hours', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
                ('zip_code', models.CharField(default='0000000', editable=False, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Consultations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=10)),
                ('time', models.CharField(max_length=10)),
                ('clinic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aidApp.clinics')),
            ],
        ),
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('clinic', models.CharField(max_length=50)),
                ('pharmacy', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(default='0000000', editable=False, max_length=400)),
                ('answer', models.CharField(default='0000000', editable=False, max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_or_complaint', models.CharField(default='0000000', editable=False, max_length=10)),
                ('patient_message', models.CharField(max_length=200)),
                ('admin_reply', models.CharField(default='0000000', editable=False, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_firstName', models.CharField(max_length=100)),
                ('patient_lastName', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=200)),
                ('appointments', models.DateTimeField(auto_now=True)),
                ('phone_number', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=100)),
                ('clinic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinics', to='aidApp.clinics')),
                ('doctor_lastName', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_lastNames', to='aidApp.clinics')),
            ],
        ),
        migrations.CreateModel(
            name='Pharmacies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pharmacy_name', models.CharField(max_length=100)),
                ('open_hours', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Health_Practitioner',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
        migrations.AddField(
            model_name='patients',
            name='pharmacy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aidApp.pharmacies'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='patient_first_name',
            field=models.ForeignKey(default='0000000', editable=False, on_delete=django.db.models.deletion.CASCADE, to='aidApp.patients'),
        ),
        migrations.AddField(
            model_name='consultations',
            name='doctor_last_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aidApp.doctors'),
        ),
        migrations.AddField(
            model_name='consultations',
            name='patient_last_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aidApp.patients'),
        ),
        migrations.AddField(
            model_name='consultations',
            name='pharmacy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aidApp.pharmacies'),
        ),
    ]
