# Generated by Django 3.2.4 on 2021-07-11 01:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aidApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('website', models.TextField(max_length=60)),
                ('located_in', models.TextField(max_length=100)),
                ('address', models.TextField(max_length=254)),
                ('hours', models.TextField(max_length=254)),
                ('appointments_url', models.URLField(max_length=20)),
                ('telephone', models.CharField(max_length=20)),
                ('question_answer', models.TextField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('service_options', models.CharField(max_length=50)),
                ('located_in', models.TextField(max_length=254)),
                ('address', models.TextField(max_length=254)),
                ('hours', models.TextField(max_length=254)),
                ('telephone', models.CharField(max_length=20)),
                ('website', models.URLField(max_length=60)),
                ('directions', models.TextField(max_length=254)),
            ],
        ),
        migrations.RemoveField(
            model_name='faq',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='createdby',
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(max_length=20)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Health_Practitioner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(max_length=20)),
                ('specialty', models.TextField(max_length=254)),
                ('health_practitioner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField(max_length=254)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aidApp.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('is_approved', models.BooleanField(default=False)),
                ('health_practitioner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aidApp.health_practitioner')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aidApp.patient')),
            ],
            options={
                'unique_together': {('health_practitioner', 'date_time')},
            },
        ),
    ]
