# Generated by Django 3.2.4 on 2021-06-29 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidApp', '0002_auto_20210628_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultations',
            name='month',
            field=models.CharField(max_length=100),
        ),
    ]
