# Generated by Django 3.2.4 on 2021-06-27 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aidApp', '0002_auto_20210625_0923'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ViewConsultations', models.CharField(max_length=100)),
                ('ViewPatients', models.CharField(max_length=100)),
                ('SeeScheduledConsultations', models.CharField(max_length=100)),
                ('ManageProfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aidApp.health_practitioner')),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Yes', models.CharField(max_length=100)),
                ('No', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ViewFeedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aidApp.health_practitioner')),
            ],
        ),
        migrations.CreateModel(
            name='Pharmacies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ViewConsultations', models.CharField(max_length=100)),
                ('ViewPatients', models.CharField(max_length=100)),
                ('SeeScheduledConsultations', models.CharField(max_length=100)),
                ('ManageProfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aidApp.health_practitioner')),
            ],
        ),
        migrations.RemoveField(
            model_name='manageprofile',
            name='MyProfile',
        ),
        migrations.RemoveField(
            model_name='manageprofile',
            name='TalkToDoctor',
        ),
        migrations.RemoveField(
            model_name='viewclinicspharminlocation',
            name='SignUp',
        ),
        migrations.RemoveField(
            model_name='viewhealthpractitioners',
            name='LoggedIn',
        ),
        migrations.RemoveField(
            model_name='viewhealthpractitioners',
            name='SignUp',
        ),
        migrations.DeleteModel(
            name='GiveFeedbackCompliants',
        ),
        migrations.DeleteModel(
            name='ManageProfile',
        ),
        migrations.DeleteModel(
            name='ViewClinicsPharmInLocation',
        ),
        migrations.DeleteModel(
            name='ViewHealthPractitioners',
        ),
    ]
