# Generated by Django 3.2.4 on 2021-07-11 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidApp', '0002_auto_20210710_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='website',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='website',
            field=models.URLField(max_length=100),
        ),
    ]
