# Generated by Django 3.2.4 on 2021-06-29 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aidApp', '0003_alter_consultations_month'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctors',
            name='password',
        ),
        migrations.RemoveField(
            model_name='doctors',
            name='pharmacy',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='appointments',
        ),
        migrations.AddField(
            model_name='patients',
            name='appointment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aidApp.doctors'),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='clinic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aidApp.pharmacies'),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now=True)),
                ('time', models.CharField(max_length=200)),
                ('login', models.CharField(default='0000000', editable=False, max_length=100)),
                ('doctors', models.ForeignKey(default='0000000', editable=False, on_delete=django.db.models.deletion.CASCADE, to='aidApp.doctors')),
            ],
        ),
    ]
