# Generated by Django 3.2.4 on 2021-06-27 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aidApp', '0003_auto_20210627_0711'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=100)),
                ('health_practitioner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aidApp.health_practitioner')),
            ],
        ),
    ]
