# Generated by Django 3.2.4 on 2021-07-30 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aidApp', '0004_auto_20210730_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='medical_history',
        ),
    ]
