# Generated by Django 3.2.4 on 2021-07-30 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidApp', '0005_remove_patient_medical_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='patient',
        ),
        migrations.AddField(
            model_name='feedback',
            name='email',
            field=models.EmailField(default=1, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='fullname',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
