# Generated by Django 3.2.4 on 2021-07-30 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aidApp', '0006_auto_20210730_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='fullname',
        ),
    ]
