# Generated by Django 3.2.4 on 2021-07-30 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aidApp', '0007_remove_feedback_fullname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='email',
        ),
    ]
