# Generated by Django 3.2.4 on 2021-07-30 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aidApp', '0009_auto_20210730_1814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='email',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='fullname',
        ),
    ]
