# Generated by Django 3.2.4 on 2021-07-30 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidApp', '0010_auto_20210730_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='email',
            field=models.EmailField(default=1, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='fullname',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
