# Generated by Django 3.2.4 on 2021-07-30 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidApp', '0011_auto_20210730_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='response_type',
            field=models.TextField(default='complaint'),
        ),
    ]
