# Generated by Django 3.2.4 on 2021-08-02 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidApp', '0013_auto_20210802_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='age',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
    ]
