# Generated by Django 3.2.4 on 2021-08-15 19:42

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('aidApp', '0016_auto_20210805_1306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='health_practitioner',
            name='clinics',
        ),
        migrations.RemoveField(
            model_name='health_practitioner',
            name='image',
        ),
        migrations.AddField(
            model_name='health_practitioner',
            name='age',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='health_practitioner',
            name='clinic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='aidApp.clinic'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='health_practitioner',
            name='gender',
            field=models.CharField(default='male', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='health_practitioner',
            name='insurance',
            field=models.TextField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='health_practitioner',
            name='language',
            field=models.CharField(default='English', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='health_practitioner',
            name='location',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='health_practitioner',
            name='name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='health_practitioner',
            name='new_patients',
            field=models.CharField(default='yes', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='app_date',
            field=models.DateField(default=datetime.datetime(2021, 8, 15, 19, 40, 37, 401020, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='patient',
            name='D_O_B',
            field=models.DateField(default=datetime.datetime(2021, 8, 15, 19, 40, 37, 389542, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='patient',
            name='telephone',
            field=phone_field.models.PhoneField(blank=True, help_text='Patient phone number', max_length=31),
        ),
    ]
