# Generated by Django 3.2.4 on 2021-08-15 19:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('aidApp', '0018_auto_20210815_1544'),
    ]

    operations = [
        migrations.RenameField(
            model_name='health_practitioner',
            old_name='clinic',
            new_name='clinics',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='app_date',
            field=models.DateField(default=datetime.datetime(2021, 8, 15, 19, 45, 34, 178858, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='patient',
            name='D_O_B',
            field=models.DateField(default=datetime.datetime(2021, 8, 15, 19, 45, 34, 166845, tzinfo=utc)),
        ),
    ]
