# Generated by Django 3.2.4 on 2021-08-15 20:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('aidApp', '0022_auto_20210815_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='health_practitioner',
            name='age',
        ),
        migrations.RemoveField(
            model_name='health_practitioner',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='health_practitioner',
            name='insurance',
        ),
        migrations.RemoveField(
            model_name='health_practitioner',
            name='language',
        ),
        migrations.RemoveField(
            model_name='health_practitioner',
            name='location',
        ),
        migrations.RemoveField(
            model_name='health_practitioner',
            name='name',
        ),
        migrations.RemoveField(
            model_name='health_practitioner',
            name='new_patients',
        ),
        migrations.AddField(
            model_name='health_practitioner',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='app_date',
            field=models.DateField(default=datetime.datetime(2021, 8, 15, 20, 6, 33, 363298, tzinfo=utc)),
        ),
        migrations.RemoveField(
            model_name='health_practitioner',
            name='clinics',
        ),
        migrations.AddField(
            model_name='health_practitioner',
            name='clinics',
            field=models.ManyToManyField(to='aidApp.Clinic'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='D_O_B',
            field=models.DateField(default=datetime.datetime(2021, 8, 15, 20, 6, 33, 351268, tzinfo=utc)),
        ),
    ]
