# Generated by Django 3.2.4 on 2021-08-15 23:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('aidApp', '0028_auto_20210815_1759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='health_practitioner',
            name='clinics',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='app_date',
            field=models.DateField(default=datetime.datetime(2021, 8, 15, 23, 20, 35, 829318, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='patient',
            name='D_O_B',
            field=models.DateField(default=datetime.datetime(2021, 8, 15, 23, 20, 35, 816313, tzinfo=utc)),
        ),
    ]
