# Generated by Django 3.2.4 on 2021-08-15 23:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('aidApp', '0029_auto_20210815_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='health_practitioner',
            name='clinics',
            field=models.ManyToManyField(to='aidApp.Clinic'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='app_date',
            field=models.DateField(default=datetime.datetime(2021, 8, 15, 23, 22, 20, 418672, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='patient',
            name='D_O_B',
            field=models.DateField(default=datetime.datetime(2021, 8, 15, 23, 22, 20, 401926, tzinfo=utc)),
        ),
    ]
