# Generated by Django 3.2.4 on 2021-08-16 00:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('aidApp', '0030_auto_20210815_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='health_practitioner',
            name='image',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='app_date',
            field=models.DateField(default=datetime.datetime(2021, 8, 16, 0, 40, 43, 623551, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='patient',
            name='D_O_B',
            field=models.DateField(default=datetime.datetime(2021, 8, 16, 0, 40, 43, 611446, tzinfo=utc)),
        ),
    ]
