# Generated by Django 3.2.4 on 2021-08-23 19:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('aidApp', '0031_auto_20210815_2040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='nature_of_enquiry',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='your_email',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='your_message',
        ),
        migrations.AddField(
            model_name='appointment',
            name='app_date_day',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31)], default=1),
        ),
        migrations.AddField(
            model_name='appointment',
            name='app_date_month',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], default=1),
        ),
        migrations.AddField(
            model_name='appointment',
            name='app_date_year',
            field=models.IntegerField(choices=[(2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024)], default=2021),
        ),
        migrations.AddField(
            model_name='appointment',
            name='appt_reason',
            field=models.TextField(default='Annual Physical Examination', max_length=200),
        ),
        migrations.AddField(
            model_name='appointment',
            name='timeslots',
            field=models.IntegerField(choices=[(0, '9:00 AM'), (1, '10:00 AM'), (2, '11:00 AM'), (3, '12:00 PM'), (4, '1:00 PM'), (5, '2:00 PM'), (6, '3:00 PM'), (7, '4:00 PM'), (8, '5:00 PM')], default=0),
        ),
        migrations.AddField(
            model_name='clinic',
            name='availability',
            field=models.TextField(default='Monday, Tuesday', max_length=60),
        ),
        migrations.AddField(
            model_name='contact',
            name='comment',
            field=models.TextField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='fname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='inquiry',
            field=models.CharField(choices=[(None, 'Nature of Inquiry'), ('feedback', 'Feedback'), ('career', 'Career'), ('support', 'Support')], default='Feedback', max_length=8),
        ),
        migrations.AddField(
            model_name='contact',
            name='lname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='health_practitioner',
            name='accepting_new_patients',
            field=models.CharField(default='Yes', max_length=3),
        ),
        migrations.AddField(
            model_name='health_practitioner',
            name='insurance_accepted',
            field=models.CharField(default='Blue Cross', max_length=200),
        ),
        migrations.AddField(
            model_name='health_practitioner',
            name='languages',
            field=models.CharField(default='English', max_length=60),
        ),
        migrations.AddField(
            model_name='health_practitioner',
            name='patient_comments',
            field=models.IntegerField(default=25),
        ),
        migrations.AddField(
            model_name='health_practitioner',
            name='professional_suffix',
            field=models.CharField(default=' MD', max_length=4),
        ),
        migrations.AddField(
            model_name='health_practitioner',
            name='rating_reviews',
            field=models.FloatField(default=4.7),
        ),
        migrations.AddField(
            model_name='health_practitioner',
            name='reviews',
            field=models.IntegerField(default=29),
        ),
        migrations.RemoveField(
            model_name='health_practitioner',
            name='clinics',
        ),
        migrations.AddField(
            model_name='health_practitioner',
            name='clinics',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='aidApp.clinic'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='health_practitioner',
            name='consultation_times',
            field=models.TextField(default='Monday - 10:00am to 11:00am', max_length=600),
        ),
        migrations.AlterField(
            model_name='health_practitioner',
            name='professional_title',
            field=models.CharField(default='Dr. ', max_length=4),
        ),
        migrations.AlterField(
            model_name='health_practitioner',
            name='specialty',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='patient',
            name='D_O_B',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='app_date',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='app_time',
        ),
    ]
